from ..event.model import EventType
from .model import Notification, NotificationType, TimeUnit

DEFAULT_NOTIFICATIONS = [
    # Service Pick-up Default Notifications
    Notification.Write(
        name="Picked up",
        message="Good news! Your items has been picked up and is being processed for order ((order_id)). We'll soon weigh it and let you know how much will be charged to your card.",
        mode=EventType.service,
        notification_type=NotificationType.on_service_pickup,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    Notification.Write(
        name="Ready for pick-up",
        message="Your items are ready for pickup! Your Order ID is ((order_id)). We will update you soon when we pick them up from ((location_name))",
        mode=EventType.service,
        notification_type=NotificationType.on_start,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    Notification.Write(
        name="Charge",
        message="Your items weigh ((weight)) ((unit)) and you were successfully charged ((currency))((amount)) for order ((order_id)). Your order is in process and we will notify you when it's available to be picked up.",
        mode=EventType.service,
        notification_type=NotificationType.on_service_charge,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    Notification.Write(
        name="User Pickup",
        message="Your fresh laundry is ready to be picked up in locker ((locker_number)) for  order ((order_id)). Please retrieve as soon as possible from ((location_name)). ((location_address)). Use the app to unlock the locker and retrieve your items.",
        mode=EventType.service,
        notification_type=NotificationType.on_service_dropoff,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    Notification.Write(
        name="Complete",
        message="Order ((order_id)) has been completed. Thank you for trusting us with your ((service)). Please return soon!",
        mode=EventType.service,
        notification_type=NotificationType.on_complete,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    # Rental Default Notifications
    Notification.Write(
        name="Transaction Starts",
        message="Order ((order_id)) has started in locker ((locker_number)) at ((location_name)). ((location_address)). You may also view your order at any time from the app.",
        mode=EventType.rental,
        notification_type=NotificationType.on_start,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    Notification.Write(
        name="Complete",
        message="Order ((order_id)) has successfully been completed. Thank you for using our service. Please return soon!",
        mode=EventType.rental,
        notification_type=NotificationType.on_complete,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    # Storage Default Notifications
    Notification.Write(
        name="Transaction Starts",
        message="Order ((order_id)) has started in locker ((locker_number)) at ((location_name)). ((location_address))",
        mode=EventType.storage,
        notification_type=NotificationType.on_start,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    Notification.Write(
        name="Complete",
        message="Order ((order_id)) has successfully been completed. Thank you for trusting us. Please return soon! ",
        mode=EventType.storage,
        notification_type=NotificationType.on_complete,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    # Delivery Default Notifications
    Notification.Write(
        name="Transaction Starts",
        message="Your transaction has started in locker ((locker_number)) at ((location_name)). ((location_address)). You may also view your order at any time from the app.",
        mode=EventType.delivery,
        notification_type=NotificationType.on_start,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    Notification.Write(
        name="Complete",
        message="Order ((order_id)) has successfully been completed. Thank you for trusting us. Please return soon! ",
        mode=EventType.delivery,
        notification_type=NotificationType.on_complete,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
    Notification.Write(
        name="Expired Package",
        message="Your parcel is going to expire in ((selected_duration)) from ((locker_number)) at ((location_name)). If you do not collect your parcel before it expires you can collect it from the front desk.",
        mode=EventType.delivery,
        notification_type=NotificationType.on_expired,
        time_amount=0,
        time_unit=TimeUnit.immediately,
        before=False,
        after=True,
        email=False,
        sms=True,
        push=False,
        email_2nd=False,
        sms_2nd=False,
        push_2nd=False,
        is_template=True,
        id_member=None,
    ),
]
